---
title: "Lung Cancer: Gaussian processes (GPLVM) with all features"
author: "Evariste Njomgue"
date: "2023-01-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Install libraries
```{r eval=FALSE, include=FALSE}
install.packages("kernlab")
```



# Load libraries
```{r}
library(kernlab)
library(ggplot2)
library(GGally)
library(pROC)
library(caret)
library(PRROC)
```

# Load data
```{r}
data = read.csv("LUNG.txt", sep = ";")
t_data = t(data)
colnames(t_data) <- data[, 1]
lung_data = t_data[-c(1), ]
# Remove row names
rownames(lung_data) <- NULL
dim(lung_data)
```

Convert to numeric
```{r}
lung_data <- apply(lung_data, 2, function(x) as.numeric(x))
typeof(lung_data[, 3])
```

# Have a look on data
```{r}
ggplot(data=as.data.frame(lung_data), aes(x=factor(lung_data[,1]))) +
  geom_bar(stat="count", fill="steelblue")
```

# 
```{r}
ggpairs(as.data.frame(lung_data), columns = 12:18, ggplot2::aes(colour=as.character(lung_data[, 1]))) + theme_bw()
```


Transform target from 1/2 to 0/1
```{r}
# Case: 2 >> 1 | Control: 1 >> 0
if (sum(lung_data[, 1] == 0) == 0) lung_data[, 1] = lung_data[, 1] - 1
# Look at first 5 rows
lung_data[1:5, 1]
```


# Have a look on data
```{r}
str(lung_data[, 1:3])
```

# Split data in train and test
```{r}
# 80 | 20
set.seed(15)
N = nrow(lung_data)
train_ratio = 0.8
indices= sample(1:N, train_ratio*N)
train_data= lung_data[indices,]
test_data= lung_data[-indices,]
#
dim(train_data)
dim(test_data)
```

#Gaussian process on the training dataset
```{r}
# Identify features to scale
feat.to.scale = colnames(train_data) != "Label"

# Fit the model
gplvm <- gausspr(x=train_data[,-1], y=factor(train_data[,1]), type="classification", scaled=TRUE, kernel="rbfdot", kpar="automatic")

```

#Have a look on the model
```{r}
gplvm
```

#the results on the test dataset
```{r}
pred_test <- predict(gplvm, test_data[,-1])
# Accuracy
mean(pred_test == test_data[, 1])

```

Confusion matrix
```{r}
confusion_mat = as.matrix(table(Actual_Values = test_data[, 1], Predicted_Values = pred_test))
print(confusion_mat)
```

```{r}
posterior <- predict(gplvm, test_data[,-1], type="probabilities")
posterior[1:5,]
```

Roc curve 
```{r}
##the second col. contains the probabilities for the case category
res.roc_tune <- roc(test_data[, 1], posterior[,2])
plot.roc(res.roc_tune, print.auc = TRUE)
```


# Compute confidence interval: for performance metrics
```{r}
#Set the same seed
set.seed(2023)
#
B.iter = 1000
B.accuracy = rep(0, 1)
B.auc = rep(0, 1)

#
N = nrow(lung_data)

# Run bootstrap
start_time <- Sys.time()
for (i in 1:B.iter){
  # Sample with replacement
  
  # Split Train/Test
  train_ratio = 0.8
  indices= sample(1:N, train_ratio*N, replace = TRUE)
  train_data= lung_data[indices,]
  test_data= lung_data[-indices,]
  
  # Train model and compute performance metrics
  gplvm <- gausspr(x=train_data[,-1], y=factor(train_data[,1]), type="classification", scaled=TRUE, kernel="rbfdot", kpar="automatic")
  
  
  # Compute and Save the bootstrap statictics
  pred_test <- predict(gplvm, test_data[,-1])
  # Accuracy
  B.accuracy[i] = mean(pred_test == test_data[, 1])
  # AUC
  posterior <- predict(gplvm, test_data[,-1], type="probabilities")
  res.roc_tune <- roc(test_data[, 1], posterior[,1])
  B.auc[i] = auc(res.roc_tune)
}
end_time <- Sys.time()
end_time-start_time
paste("CI Bootstrap - computing time: ", end_time-start_time)
```


# 95% CI
```{r}
paste("Accuracy 95% CI: ", quantile(B.accuracy, probs = c(0.025, 0.975)))
paste("AUC 95% CI: ", quantile(B.auc, probs = c(0.025, 0.975)))
```


# Histogramms
```{r}
# replacement TRUE
hist(B.accuracy)
hist(B.auc)
```














